application/velleda/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve

from velleda import settings
from whiteboard.dash_apps import *

dash_apps = [room_app, stay_table_app]

urlpatterns = [
    path('whiteboard/', include('whiteboard.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('django_plotly_dash/', include('django_plotly_dash.urls')),
    path('api-auth/', include('rest_framework.urls'))
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))
else:
    urlpatterns.append(
        re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT,}),
    )

application/whiteboard/urls.py
from django.urls import path, include
from rest_framework import routers

from .views import *
from .viewsets import *

router = routers.DefaultRouter()
router.register(r'stays', StayViewSet)
router.register(r'patientpositions', PatientPositionViewSet)
router.register(r'ventilatorchecks', VentilatorChecksViewSet)
router.register(r'biologicalreadings', BiologicalReadingViewSet)

urlpatterns = [
    path('home/', WhiteboardView.as_view(), name='home'),
    path('room/<int:pk>/', RoomView.as_view(), name='room_detail'),
    path('stay/<int:pk>/', StayView.as_view(), name='stay_detail'),
    path('api/', include(router.urls))
]

application/whiteboard/models.py
import datetime
import hashlib

from django.db import models


class Patient(models.Model):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    ipp = models.CharField(max_length=200)
    birth_date = models.DateField()
    weight = models.IntegerField(blank=True, null=True)
    height = models.IntegerField(blank=True, null=True)

    GENDER = (
        ('M', 'Homme'),
        ('F', 'Femme'),
    )
    gender = models.CharField(
        max_length=10,
        choices=GENDER,
        null=True,
        verbose_name='Genre',
    )

    @property
    def age(self):
        if not self.birth_date:
            return None
        today = datetime.date.today()
        return int((today-self.birth_date).days / 365)  # TODO check with Dad if ok

    @property
    def title(self):
        if self.gender == 'M':
            return 'Mr'
        elif self.gender == 'F':
            return 'Mme'
        return 'N/A'

    @property
    def tidal(self):
        if self.gender and self.height:
            if self.gender == 'M':
                x = 50
            else:
                x = 45.5
            vt = round(6 * (x + 0.91 * (self.height - 152.4)))
            return vt
        else:
            return None

    @property
    def current_stay(self):
        opened_stays = self.stay_set.filter(end_date__isnull=True)
        if len(opened_stays) == 1:
            return opened_stays[0]
        elif len(opened_stays) > 1:
            # TODO specifiy error here
            return -1
        return None

    def __str__(self):
        return "%s %s [%s]" % (self.last_name.upper(), self.first_name, self.ipp)

    @property
    def current_position(self):
        return self.patientposition_set.order_by('-position_date')[0]


class PatientPosition(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)

    POS = (
        ('D', 'Dorsale'),
        ('V', 'Ventrale'),
        ('SLD', 'Semi-Latérale droite'),
        ('SLG', 'Semi-latérale gauche'),
        ('LG', 'Latérale gauche'),
        ('LD', 'Latérale droite'),
    )
    POS_DICT = {
        'D': 'dorsale',
        'V': 'ventrale',
        'SLD': 'semi-Latérale droite',
        'SLG': 'semi-latérale gauche',
        'LG': 'latérale gauche',
        'LD': 'latérale droite',
    }

    position = models.CharField(max_length=200, choices=POS)
    position_date = models.DateTimeField()
    comment = models.TextField(null=True, blank=True)
    creation_date = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True)

    @property
    def position_long(self):
        return self.POS_DICT.get(self.position, None)

    @property
    def position_age(self):
        return (datetime.datetime.now() - self.position_date).total_seconds() / 3600

    def __str__(self):
        return "%s in position %s" % (self.patient, self.position)


class Stay(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    iep = models.CharField(max_length=200)
    start_date = models.DateTimeField()
    end_date = models.DateTimeField(null=True, blank=True)
    comment = models.TextField(null=True, blank=True)
    # TODO from, to ?

    @property
    def duration(self): # TODO check with Dad if ok
        if self.end_date:
            return (self.end_date - self.start_date).days
        return (datetime.datetime.utcnow() - self.start_date).days

    @property
    def current_assignment(self):
        return self.assignmentstaff_set.order_by('-start_date').first()

    @property
    def last_biological_reading(self):
        return self.biologicalreading_set.order_by("-reading_time").first()

    def __str__(self):
        if self.end_date:
            return "%s from %s to %s" % (self.patient, self.start_date.date(), self.end_date.date())
        return "%s from %s" % (self.patient, self.start_date.date())


class Room(models.Model):
    name = models.CharField(max_length=200)


class Bed(models.Model):
    room = models.ForeignKey(Room, on_delete=models.PROTECT)
    name = models.CharField(max_length=200)

    def __str__(self):
        return "%s in %s" % (self.name, self.room.name)


class Ventilator(models.Model):
    room = models.ForeignKey(Room, on_delete=models.PROTECT)
    name = models.CharField(max_length=200)

    @property
    def last_check(self):
        checks = list(self.ventilatorchecks_set.order_by('-pk'))
        if checks:
            return checks[0]
        return VentilatorChecks()

    def __str__(self):
        return "%s in %s" % (self.name, self.room.name)


class VentilatorChecks(models.Model):
    ventilator = models.ForeignKey(Ventilator, on_delete=models.PROTECT)
    is_done = models.BooleanField(default=False)
    status = models.CharField(max_length=200, null=True, blank=True)
    comment = models.TextField(null=True, blank=True)
    check_time = models.DateTimeField()
    creation_date = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True)

    @property
    def name(self):
        return self.ventilator.name

    @property
    def check_age(self):
        if self.check_time:
            return round((datetime.datetime.now() - self.check_time).total_seconds() / 3600, 1)

    @property
    def check_age_str(self):
        if self.check_time:
            return "%sh" % self.check_age
        return "N/A"


class PatientLocation(models.Model):
    patient = models.OneToOneField(Patient, on_delete=models.CASCADE)
    bed = models.OneToOneField(Bed, on_delete=models.CASCADE)
    ventilator = models.OneToOneField(Ventilator, on_delete=models.CASCADE)

    def __str__(self):
        return "%s in bed %s with ventilator %s" % (self.patient, self.bed.name, self.ventilator.name)


class Staff(models.Model):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)

    ROLE = (
        ('MED', 'Médecin'),
        ('IDE', 'Infirmière'),
        ('AS', 'Aide-soignante'),
        ('ASH', 'ASH'),
        ('BR', 'Brancardier'),
        ('DV', 'Team DV'),
    )
    role = models.CharField(max_length=200, choices=ROLE)
    phone = models.IntegerField()

    def __str__(self):
        return "%s %s" % (self.first_name, self.last_name.upper())


class Team(models.Model):
    medical_staff = models.ForeignKey(Staff, on_delete=models.CASCADE, related_name='medical_staff')
    paramedical_staff = models.ForeignKey(Staff, on_delete=models.CASCADE, related_name='paramedical_staff')
    as_staff = models.ForeignKey(Staff, on_delete=models.CASCADE, related_name='as_staff')

    def __str__(self):
        return "%s - %s - %s" % (self.medical_staff, self.paramedical_staff, self.as_staff)


class AssignmentStaff(models.Model):
    stay = models.ForeignKey(Stay, on_delete=models.CASCADE)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    start_date = models.DateTimeField()
    end_date = models.DateTimeField(null=True, blank=True)

    @property
    def patient(self):
        return self.stay.patient

    @property
    def bed(self):
        return self.stay.patient.patientlocation.bed

    def ventilator(self):
        return self.stay.patient.patientlocation.ventilator

    def __str__(self):
        return "%s - %s - %s" % (self.stay.patient, self.team, self.start_date)


class BiologicalReading(models.Model):
    stay = models.ForeignKey(Stay, on_delete=models.CASCADE, verbose_name='Séjour')
    reading_time = models.DateTimeField(verbose_name='Date relevé')
    ph = models.FloatField(blank=True, null=True, verbose_name='pH')
    pao2 = models.IntegerField(blank=True, null=True, verbose_name='PaO2')
    pco2 = models.IntegerField(blank=True, null=True, verbose_name='PCO2')
    hco3 = models.FloatField(blank=True, null=True, verbose_name='HCO3')
    sat = models.IntegerField(blank=True, null=True, verbose_name='Saturation')
    hb = models.FloatField(blank=True, null=True, verbose_name='Hb')
    ht = models.FloatField(blank=True, null=True, verbose_name='Ht')
    creat = models.FloatField(blank=True, null=True, verbose_name='Créatininémie')
    clairance = models.FloatField(blank=True, null=True, verbose_name='Clairance')
    k = models.FloatField(blank=True, null=True, verbose_name='K')
    na = models.FloatField(blank=True, null=True, verbose_name='Na')
    peep = models.IntegerField(blank=True, null=True, verbose_name='PEEP')
    fio2 = models.FloatField(blank=True, null=True, verbose_name='FiO2')
    diurese = models.IntegerField(blank=True, null=True, verbose_name='Diurèse')
    is_deleted = models.BooleanField(default=False)

    @property
    def pao2_fio2(self):
        if self.pao2 and self.fio2 and self.fio2 != 0:
            return round(self.pao2 / self.fio2, 2)
        return "N/A"

    def __str__(self):
        return "%s at %s" % (self.stay, self.reading_time)

    def __hash__(self):
        m = hashlib.sha512()
        m.update(str(self.to_dict()).encode("ascii"))
        return m.hexdigest()

application/whiteboard/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.template.defaulttags import register
from django.views import generic

from whiteboard.models import Room, Stay, PatientPosition, Ventilator


@register.filter
def get_item(dictionary, key):
    return dictionary.get(key)


class WhiteboardView(LoginRequiredMixin, generic.ListView):
    model = Room
    template_name = "whiteboard/home.html"


class RoomView(LoginRequiredMixin, generic.DetailView):
    model = Room
    template_name = "whiteboard/room.html"


class StayView(LoginRequiredMixin, generic.DetailView):
    model = Stay
    template_name = "whiteboard/stay.html"

    POS_IMAGES = {
        'D': 'img/dorsal.png',
        'V': 'img/ventral.png',
        'SLD': 'img/semi_lateral_droit.png',
        'SLG': 'img/semi_lateral_gauche.png',
        'LG': 'img/lateral_gauche.png',
        'LD': 'img/lateral_droit.png',
    }

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["position_choices"] = PatientPosition.POS
        context["ventilator_choices"] = [(v.pk, v.name) for v in Ventilator.objects.all()]
        context["position_images"] = self.POS_IMAGES
        return context

application/whiteboard/templates/whiteboard/base.html
<!DOCTYPE html>
{% load static %}
{% load plotly_dash%}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Pangolid</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/fontawesome.min.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/tempusdominus.css'%}">
    <script src="{% static 'js/moment.js' %}"></script>
    <script src="{% static 'js/tempusdominus.min.js' %}"></script>
    {% plotly_header %}
    {% block extrahead %}
    {% endblock extrahead %}
</head>
<body>
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <img class="pangolid" src="{% static 'img/pangolid.png' %}" />
        <li class="breadcrumb-item active" aria-current="page"><a href="{% url 'logout' %}"><i class="fas fa-sign-in-alt"></i> Déconnexion</a></li>
        {% block breadcrumb %}
        {% endblock breadcrumb %}
      </ol>
    </nav>
    {% block content %}
    {% endblock content %}
    {% plotly_footer %}
    {% block extrabottom %}
    {% endblock extrabottom %}
</body>
</html>

application/whiteboard/templates/whiteboard/home.html
{% extends 'whiteboard/base.html' %}

{% load static %}
{% load plotly_dash %}

{% block breadcrumb %}
<li class="breadcrumb-item" aria-current="page"><i class="fas fa-home"></i> Accueil</li>
{% endblock breadcrumb %}

{% block content %}
<div class="container-fluid whiteboard">
    <div class="row">
        <div class="col">
            <h2 class="page-title">Salles</h2>
        </div>
    </div>
    <div class="row whiteboard">
        <div class="col">
            <div class="list-group">
                {% for room in room_list %}
                      <a href="{% url 'room_detail' room.id %}" class="list-group-item list-group-item-action">{{ room.name }}</a>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock content %}

application/whiteboard/templates/whiteboard/room.html
{% extends 'whiteboard/base.html' %}

{% load static %}
{% load plotly_dash %}

{% block breadcrumb %}
<li class="breadcrumb-item" aria-current="page"><a href="{% url 'home' %}"><i class="fas fa-home"></i> Accueil</a></li>
<li class="breadcrumb-item active">Salle</li>
{% endblock breadcrumb %}

{% block content %}
<div class="container-fluid whiteboard">
    <div class="row">
        <div class="col">
            <h2 class="page-title">{{ room.name }}</h2>
            <h3 class="lead">{% now "d/m/Y" %}</h3>
        </div>
    </div>
    <div class="row whiteboard">
        <div class="col">
            {% plotly_direct name='RoomWhiteboard' %}
        </div>
    </div>
</div>
{% endblock content %}

application/whiteboard/templates/whiteboard/stay.html
{% extends 'whiteboard/base.html' %}

{% load static %}
{% load plotly_dash %}

{% block extrahead %}
{% endblock extrahead %}

{% block extrabottom %}
<script src="{% static 'js/ajaxform.js' %}"></script>
<script src="{% static 'js/stay.js' %}"></script>
<script src="/static/rest_framework/js/csrf.js"></script>
{% endblock extrabottom %}

{% block breadcrumb %}
<li class="breadcrumb-item" aria-current="page"><a href="{% url 'home' %}"><i class="fas fa-home"></i> Accueil</a></li>
<li class="breadcrumb-item"><a href="{% url 'room_detail' 1 %}">Salle</a></li>
<li class="breadcrumb-item active" aria-current="page">Patient</li>
{% endblock breadcrumb %}

{% block content %}
<script>
  var position_images = {
    {% for pos, img in position_images.items %}
    {{ pos }}: "{% static img %}",
    {% endfor %}
  }
</script>
<div class="container-fluid">
    <div class="row page-title">
        <div class="col">
            <h2>{{ stay.patient.title }} {{ stay.patient.first_name }} {{ stay.patient.last_name|upper }}</h2>
            <h6 class="lead">Né{% if stay.patient.gender == 'F' %}e{% endif %} le {{ stay.patient.birth_date|date:"SHORT_DATE_FORMAT" }} - {{ stay.patient.age }} ans</h6>
        </div>
        <div class="col-3 float-right">
            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    <strong>Médecin</strong>
                    <span class="float-right">{{ stay.current_assignment.team.medical_staff }}
                        <i class="fas fa-phone"></i>
                        {{ stay.current_assignment.team.medical_staff.phone }}
                    </span>
                </li>
                <li class="list-group-item">
                    <strong>IDE</strong>
                    <span class="float-right">{{ stay.current_assignment.team.paramedical_staff}}
                        <i class="fas fa-phone"></i>
                        {{ stay.current_assignment.team.paramedical_staff.phone }}
                    </span>
                </li>
            </ul>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="shadow-none p-3 mb-5 bg-light rounded">
                <div class="row">
                    <div class="col">
                        <h5 class="card-title">Séjour</h5>
                        <h6 class="card-subtitle mb-2 text-muted">Entré{% if stay.patient.gender == 'F' %}e{% endif %} le {{ stay.start_date|date:"d/m/Y" }} - Jour {{ stay.duration }}</h6>
                        <p class="card-text"><i class="fas fa-procedures"></i> Lit {{ stay.patient.patientlocation.bed.name }}</p>
                        <p class="card-text">
                            <i class="fas fa-lungs"></i> Respirateur {{ stay.patient.patientlocation.ventilator.name }} vérifié il y a <span id="ventilator_last_check_age">{{ stay.patient.patientlocation.ventilator.last_check.check_age }}</span> heures
                            <br /><a href="#" class="card-link" data-toggle="modal" data-target="#stay-modal-ventilator">Editer</a>
                        </p>
                    </div>
                    <div class="col-6 text-center">
                        <h5 class="card-title text-center">Position <span id="position_name">{{ stay.patient.current_position.position_long }}</span></h5>
                        <h6 class="card-subtitle mb-2 text-muted">
                            depuis <span id="position_age">{{ stay.patient.current_position.position_age|floatformat }}</span> heures
                        </h6>
                        <div>
                            <img id="stay-position-image" src="{% static position_images|get_item:stay.patient.current_position.position %}" height="120"/>
                        </div>
                        <a href="#" class="card-link" data-toggle="modal" data-target="#stay-modal-position">Editer</a>
                    </div>
                    <div class="col-3">
                        <h5 class="card-title">
                            Notes
                            <span id="stay-edit-comment-success" hidden><i class="fas fa-check-circle text-success"></i></span>
                            <span id="stay-edit-comment-error" hidden><i class="fas fa-times-circle text-danger"></i></span>
                        </h5>
                        <form id="stay-edit-comment" data-method="PUT" action="{% url 'stay-detail' stay.id %}">
                            <div class="form-group" style="margin-bottom: 8px;">
                                <textarea class="form-control" id="stay-comment" name="comment" rows="4">{{ stay.comment }}</textarea>
                            </div>
                            <div class="form-actions">
                                <button class="btn btn-sm btn-secondary d-inline-block card-link">Enregistrer notes</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="row">
                <div class="col">
                    <h3 class="display-5 text-center">
                        PaO<sub>2</sub>/FIO<sub>2</sub>
                        <span class="text-primary">{{stay.last_biological_reading.pao2_fio2|floatformat:0}}</span>
                        <small class="text-muted">mmHg</small>
                    </h3>
                </div>
                <div class="col">
                    <h3 class="display-5 text-center">
                        FIO<sub>2</sub>
                        <span class="text-primary">{% widthratio stay.last_biological_reading.fio2 1 100 %}%</span>
                    </h3>
                </div>
                <div class="col">
                    <h3 class="display-5 text-center">
                        PaO<sub>2</sub>
                        <span class="text-primary">{{stay.last_biological_reading.pao2|floatformat:0}}</span>
                        <small class="text-muted">mmHg</small>
                    </h3>
                </div>
                <div class="col">
                    <h3 class="display-5 text-center">
                        PEEP
                        <span class="text-primary">{{stay.last_biological_reading.peep|floatformat:0}}</span>
                        <small class="text-muted">cm H<sub>2</sub>O</small>
                    </h3>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    {% plotly_direct name='StayTable' %}
                </div>
            </div>
        </div>
    </div>
</div>
{% include "whiteboard/modals/ventilator_check.html" %}
{% include "whiteboard/modals/position_change.html" %}
{% endblock content %}